import type { Metadata } from "next";
import "./globals.css";
import { Nav } from "./components/lib/03-organisms";

const NAV_LINKS = ['portfolio', 'about', 'contact'];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Nav
          links={NAV_LINKS}
        />
        {children}
      </body>
    </html>
  );
}
